import type L from 'leaflet';

export type Filters = {
  readonly lot?: string;
  readonly block?: string;
  readonly section?: string;
};

export interface IParcelsError {
  readonly invalidAddress: boolean;
  readonly incompleteAddress: boolean;
}

export interface CustomRoutingControlOptions
  extends L.Routing.RoutingControlOptions {
  draggableWaypoints?: boolean;
}

// SUPABASE TYPES
export interface Parcel {
  readonly account_number?: string | null;
  readonly address?: string | null;
  readonly address1?: string | null;
  readonly address2?: string | null;
  readonly address_source?: string | null;
  readonly ag1_acres?: string | null;
  readonly ag2_acres?: string | null;
  readonly ag3_acres?: string | null;
  readonly ag4_acres?: string | null;
  readonly ag5_acres?: string | null;
  readonly ag6_acres?: string | null;
  readonly ag7_acres?: string | null;
  readonly ag8_acres?: string | null;
  readonly agval?: string | null;
  readonly alt_parcelnumb1?: string | null;
  readonly alt_parcelnumb3?: string | null;
  readonly alternate_?: string | null;
  readonly ambulanc_1?: string | null;
  readonly ambulance1?: string | null;
  readonly ambulance_?: string | null;
  readonly app_ag_bld?: string | null;
  readonly app_ag_lan?: string | null;
  readonly app_com_bl?: string | null;
  readonly app_com_la?: string | null;
  readonly app_res_bl?: string | null;
  readonly app_res_la?: string | null;
  readonly asr_neighb?: string | null;
  readonly base_area?: string | null;
  readonly block?: string | null;
  readonly book?: string | null;
  readonly careof?: string | null;
  readonly census_block?: number | null;
  readonly census_blockgroup?: number | null;
  readonly census_tract?: number | null;
  readonly census_zcta?: number | null;
  readonly city?: string | null;
  readonly city1?: string | null;
  readonly city2?: string | null;
  readonly city_mun_1?: string | null;
  readonly city_mun_2?: string | null;
  readonly city_munic?: string | null;
  readonly com_acres?: string | null;
  readonly coname1_ad?: string | null;
  readonly coname2_ad?: string | null;
  readonly county?: string | null;
  readonly county_amt?: string | null;
  readonly county_cod?: string | null;
  readonly county_nam?: string | null;
  readonly county_r_1?: string | null;
  readonly deedacres?: string | null;
  readonly deedbook2?: string | null;
  readonly deeddate2?: string | null;
  readonly deeded_acres?: string | null;
  readonly document_1?: string | null;
  readonly document_n?: string | null;
  readonly drainage_a?: string | null;
  readonly fire_amt?: string | null;
  readonly fire_code?: string | null;
  readonly fire_name?: string | null;
  readonly geoid?: number | null;
  readonly gisacre?: number | null;
  readonly gross_acre?: string | null;
  readonly health_c_1?: string | null;
  readonly health_c_2?: string | null;
  readonly health_cen?: string | null;
  readonly improvval?: string | null;
  readonly land_use?: string | null;
  readonly landval?: string | null;
  readonly legaldesc: string;
  readonly library_am?: string | null;
  readonly library_co?: string | null;
  readonly library_na?: string | null;
  readonly ll_gisacre?: number | null;
  readonly ll_gissqft?: number | null;
  readonly ll_last_refresh?: string | null;
  readonly ll_stable_id?: string | null;
  readonly ll_stack_uuid?: string | null;
  readonly ll_updated_at?: string | Date | null; // timestamp with time zone
  readonly ll_uuid?: string | null;
  readonly location_name?: string | null;
  readonly lots?: string[] | null;
  readonly lot_dimens?: string | null;
  readonly mail_addno?: string | null;
  readonly mail_addpref?: string | null;
  readonly mail_address2?: string | null;
  readonly mail_addstr?: string | null;
  readonly mail_addstsuf?: string | null;
  readonly mail_addsttyp?: string | null;
  readonly mail_city?: string | null;
  readonly mail_country?: string | null;
  readonly mail_state2?: string | null;
  readonly mail_unit?: string | null;
  readonly mail_urbanization?: string | null;
  readonly mail_zip?: string | null;
  readonly mailadd?: string | null;
  readonly mailto_nam?: string | null;
  readonly main_base_?: string | null;
  readonly mapacres?: string | null;
  readonly name1?: string | null;
  readonly name2?: string | null;
  readonly neighborhood?: string | null;
  readonly neighborhood_code?: string | null;
  readonly noncolle_1?: string | null;
  readonly noncolle_2?: string | null;
  readonly noncollect?: string | null;
  readonly numrooms?: string | null;
  readonly numstories?: string | null;
  readonly numunits?: string | null;
  readonly nursing__2?: string | null;
  readonly original_address?: string | null;
  readonly original_mailing_address?: string | null;
  readonly other_di_1?: string | null;
  readonly other_di_2?: string | null;
  readonly other_dist?: string | null;
  readonly owner?: string | null;
  readonly owner1_id?: number | null;
  readonly owner2?: string | null;
  readonly owner2_id?: string | null;
  readonly owner3?: string | null;
  readonly owner4?: string | null;
  readonly ownfrst?: string | null;
  readonly ownlast?: string | null;
  readonly owntype?: string | null;
  readonly page?: string | null;
  readonly pageno2?: string | null;
  readonly parcelnumb?: string | null;
  readonly parcelnumb_no_formatting: string;
  readonly parval?: string | null;
  readonly parvaltype?: string | null;
  readonly path?: string | null;
  readonly plat?: string | null;
  readonly plss_range?: string | null;
  readonly plss_section?: string | null;
  readonly plss_township?: string | null;
  readonly previous_owner?: string | null;
  readonly property_n?: number | null;
  readonly qoz?: string | null;
  readonly qoz_tract?: string | null;
  readonly recrdareano?: string | null;
  readonly recrdareatx?: string | null;
  readonly res_acres?: string | null;
  readonly reviseddate?: string | null;
  readonly road_amt?: string | null;
  readonly road_code?: string | null;
  readonly road_name?: string | null;
  readonly rural_town?: string | null;
  readonly saddno?: string | null;
  readonly saddpref?: string | null;
  readonly saddstr?: string | null;
  readonly saddstsuf?: string | null;
  readonly saddsttyp?: string | null;
  readonly saledate?: string | null;
  readonly saleprice?: string | null;
  readonly school_amt?: string | null;
  readonly school_cod?: string | null;
  readonly school_nam?: string | null;
  readonly scity?: string | null;
  readonly senior_c_1?: string | null;
  readonly senior_c_2?: string | null;
  readonly senior_cen?: string | null;
  readonly sheltere_1?: string | null;
  readonly situs_stat?: string | null;
  readonly situsaddre?: string | null;
  readonly sourceurl?: string | null;
  readonly special__2?: string | null;
  readonly sqft?: string | null;
  readonly state1?: string | null;
  readonly state2?: string | null;
  readonly state_amt?: string | null;
  readonly state_code?: string | null;
  readonly state_name?: string | null;
  readonly state_parcelnumb?: string | null;
  readonly struct?: string | null;
  readonly structno?: string | null;
  readonly structstyle?: string | null;
  readonly subdivision?: string | null;
  readonly sunit?: string | null;
  readonly surtax_amt?: string | null;
  readonly surtax_cod?: string | null;
  readonly surtax_nam?: string | null;
  readonly szip?: number | null;
  readonly szip5?: number | null;
  readonly tax_billed?: string | null;
  readonly tax_code?: number | null;
  readonly tax_id?: string | null;
  readonly tax_status?: string | null;
  readonly taxamt?: string | null;
  readonly taxyear?: string | null;
  readonly tif_dist_2?: string | null;
  readonly total_app_?: string | null;
  readonly township_name?: string | null;
  readonly unmodified_owner?: string | null;
  readonly urbanization?: string | null;
  readonly usecode?: string | null;
  readonly usedesc?: string | null;
  readonly watershe_1?: string | null;
  readonly yearbuilt?: string | null;
  readonly zip1?: string | null;
  readonly zip2?: string | null;
  readonly zoning?: string | null;
  readonly zoning_description?: string | null;
  readonly geometry?: string | null;
  readonly section?: string | null;
}

export type Database = {
  public: {
    Tables: {
      parcels: {
        Row: Parcel;
        // Insert: ParcelInsert;
        // Update: ParcelUpdate;
      };
    };
  };
};
